services:
  db:
    image: mysql:latest
    container_name: ia_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # port Windows -> port Docker
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ia_network

volumes:
  db_data:

networks:
  ia_network:
